[package]
name = "site"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
pulldown-cmark = "0.12.2"
rinja = { version = "0.3.5", features = ["code-in-doc"] }
serde = { version = "1.0.216", features = ["derive"] }
syntect = "5.2.0"
tiny_http = "0.12.0"
toml = "0.8.19"
